# ===================================================================
# Fichier de configuration principal de l'application DOBI
# ===================================================================

# Adresse des serveurs Kafka (s\u00c3\u00a9par\u00c3\u00a9s par des virgules si plusieurs)
kafka.bootstrap.servers=10.242.14.3:7092

# Topic Kafka pour les donn\u00c3\u00a9es des tags
kafka.topic.tags.data=dobi.tags.data

# ===================================================================
# Configuration InfluxDB
# ===================================================================
influxdb.url=http://10.242.14.4:8086
influxdb.token=dob!token
influxdb.org=DOBI_Org
influxdb.bucket=dobi_tags_data


# ===================================================================
# VAPID Keys for Web Push Notifications
#
# Public Key:
# BOsGzQ9Byvn8UtegereDNS5foq0HaiGJzU9lNSJhwL5f_tLLVva8iBffrMpGqaaZtmrIKO0gKwVamhHNwMqKlkc
# Private Key:
# OwYzmQjLL2IzGwl6esElVMHHgvxWwhNOwyewcClAp-k
# ===================================================================
vapid.public.key=BOsGzQ9Byvn8UtegereDNS5foq0HaiGJzU9lNSJhwL5f_tLLVva8iBffrMpGqaaZtmrIKO0gKwVamhHNwMqKlkc
vapid.private.key=OwYzmQjLL2IzGwl6esElVMHHgvxWwhNOwyewcClAp-k
vapid.subject=mailto:raphael.hendrick@castel-afrique.com



# ===================================================================
# Configuration de la S\u00e9curit\u00e9 et des CORS
# ===================================================================
# Liste des origines autoris\u00e9es pour les requ\u00eates CORS et WebSocket.
# S\u00e9parez les URL par une virgule.
# IMPORTANT : Mettez \u00e0 jour cette ligne avec votre URL ngrok lorsque vous l'utilisez.
dobi.cors.allowed-origins=http://localhost:3000,https://localhost:3000,http://10.242.14.3:3000,https://10.242.14.3:3000,https://60017e67bdfa.ngrok-free.app


# Fait en sorte que le serveur web int\u00e9gr\u00e9 \u00e9coute sur toutes les adresses IP
# de la machine, et pas seulement sur localhost.
server.address=0.0.0.0

